# Generated by Django 3.1.4 on 2020-12-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='field_buzz_reference',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
