# Generated by Django 3.1.4 on 2020-12-12 03:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_uploader', '0002_auto_20201211_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='name_of_university',
            field=models.CharField(default=' ', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='cgpa',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2.0), django.core.validators.MaxValueValidator(4.0)]),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='current_work_place_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='experience_in_months',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
